services:
  - type: web
    name: automata-compiler-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: .
    healthCheckPath: /api/health 